### ISSUE TITLE
Not working with 0.219.14 - Bog Witch

### ISSUE THREAD

**Issue by LordDelacroix** [shudnal/MoreGatesExtended#2]
Not working for me under the new Bog Witch update, Game is unplayable, and I get this exception in the BepInEx window:

[Info   :   BepInEx] Loading [More Gates Extended 1.0.2]
[Info   :Jotunn.Main] Initializing LocalizationManager
[Info   :Jotunn.Main] Initializing PieceManager
[Error  : Unity Log] MissingFieldException: Field not found: System.Collections.Generic.List`1<string> .Hud.m_buildCategoryNames Due to: Could not find field in class
Stack trace:
Jotunn.Managers.PieceManager.AddPieceCategory (System.String name) (at D:/Projects/Jotunn/JotunnLib/Managers/PieceManager.cs:294)
Jotunn.Entities.CustomPiece.set_Category (System.String value) (at D:/Projects/Jotunn/JotunnLib/Entities/CustomPiece.cs:44)
Jotunn.Entities.CustomPiece..ctor (UnityEngine.AssetBundle assetBundle, System.String assetName, System.Boolean fixReference, Jotunn.Configs.PieceConfig pieceConfig) (at D:/Projects/Jotunn/JotunnLib/Entities/CustomPiece.cs:201)
MoreGatesExtended.MoreGatesExtended.LoadAsset (System.String name, Jotunn.Configs.RequirementConfig[] requirements) (at <b96e2637a5074fbab9c53fabb84f0117>:0)
MoreGatesExtended.MoreGatesExtended.RegisterPrefabs () (at <b96e2637a5074fbab9c53fabb84f0117>:0)
MoreGatesExtended.MoreGatesExtended.Awake () (at <b96e2637a5074fbab9c53fabb84f0117>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.GameObject:.cctor()
PlatformTools.Common.SingletonMonoBehaviour`1:get_Instance()
PlatformTools.PlatformManagerInitializer:OnRuntimeMethodLoad()

Let me know if you need more

**Comment by shudnal** [comment]
What's the version of your Jotunn?

**Comment by LordDelacroix** [comment]
Jotun is 2.21.1.0 - just upgraded to 2.21.2.0 and it's WORKING! WOOT!!  Sorry to bother you! BTWE Where can I buy you a beer or a coffee?

**Comment by shudnal** [comment]
Don't worry, just continue using the mod and enjoy.
